#!/usr/bin/env python3
"""Render Lecture 5's saved experiment as vector PGFPlots; no refitting.

The main experiment calls write_plots automatically. To redraw saved results:
    python3 scripts/lecture05_synthetic_plots.py
Only the Python standard library is needed to write the plot source.
Compile the lecture with its usual builder to render the vector figure.
"""
import argparse
import json
import math
from pathlib import Path


def coordinates(xs, ys):
    points = list(zip(xs, ys))
    if not all(math.isfinite(x) and math.isfinite(y) for x, y in points):
        raise ValueError("Nonfinite plotted coordinate; do not silently omit trials")
    return "\n".join(f"({x:.12g},{y:.12g})" for x, y in points)


def curve(xs, ys, style, legend=None):
    text = "\\addplot[" + style + "] coordinates {\n" + coordinates(xs, ys) + "\n};\n"
    if legend:
        text += "\\addlegendentry{" + legend + "}\n"
    return text


def axis(body, options):
    return ("\\begin{tikzpicture}\n\\begin{axis}[lFivePlot," + options + "]\n"
            + body + "\\end{axis}\n\\end{tikzpicture}\n")


def write_plots(results, output_dir):
    example = results["example"]
    trials = results["trials"]
    config = results["config"]
    selected = next(t for t in trials
                    if t["n"] == example["n"] and t["seed"] == example["seed"])
    time = example["time"]
    mean = example["true_mean"]
    ar = example["ar_mean"]
    sub = example["subspace_mean"]
    truth_style = "black,line width=1pt,no marks"
    ar_style = "orange!85!black,line width=.7pt,no marks"
    sub_style = "courseblue,line width=1pt,dashed,no marks"
    full_width = r"width=.98\linewidth,xmin=1,xmax=" + str(time[-1])
    top = axis(
        curve(time, mean, truth_style, "True mean")
        + curve(time, ar, ar_style, "AR(32)")
        + curve(time, sub, sub_style, "Rank-one state"),
        full_width + r",height=47mm,ylabel={Conditional mean},xticklabels=\empty,"
        + r"enlarge y limits=.24,legend columns=3,"
        + r"legend style={at={(.5,.98)},anchor=north},"
        + r"title={(a) Held-out predictions: \(T=" + str(example["n"])
        + r"\), seed " + str(example["seed"]) + "}")
    errors = axis(
        curve(time, [a - m for a, m in zip(ar, mean)], ar_style)
        + curve(time, [s - m for s, m in zip(sub, mean)], sub_style)
        + curve([time[0], time[-1]], [0, 0], "black!50,densely dotted,no marks"),
        full_width + r",height=39mm,ylabel={Prediction error},"
        + r"xlabel={Held-out test step},title={(b) Predicted mean minus true mean}")
    lags = list(range(1, 65))
    coefficients = axis(
        curve(lags, [config["c"] * config["ell"]
                    * (config["a"] - config["ell"] * config["c"]) ** (j - 1)
                    for j in lags], truth_style)
        + curve(lags, selected["coefficients"] + [0.0] * (64 - config["p"]), ar_style)
        + curve(lags, [selected["c"] * selected["f"] ** (j - 1) * selected["ell"]
                       for j in lags], sub_style),
        r"width=\linewidth,height=60mm,xmin=1,xmax=64,"
        + r"xlabel={Lag},ylabel={Coefficient},title={(c) Shared lag structure}")
    all_errors = [t[method]["excess_mse"] for t in trials for method in ("ar", "subspace")]
    if min(all_errors) <= 0:
        raise ValueError("Log plot requires positive errors; do not omit a zero-error fit")
    lower = 10 ** math.floor(math.log10(min(all_errors)))
    upper = 10 ** math.ceil(math.log10(max(all_errors)))
    scatter_body = curve([lower, upper], [lower, upper],
                         "black!50,dashed,no marks,forget plot")
    for n, style in [(256, "black!65,mark=*"),
                     (1024, "courseblue,mark=triangle*"),
                     (4096, "teal!75!black,mark=square*")]:
        group = [t for t in trials if t["n"] == n]
        scatter_body += curve([t["ar"]["excess_mse"] for t in group],
                              [t["subspace"]["excess_mse"] for t in group],
                              "only marks,mark size=1.25pt," + style, rf"\(T={n}\)")
    unstable = [t for t in trials if t["radius_subspace"] >= 1]
    scatter_body += curve([t["ar"]["excess_mse"] for t in unstable],
                          [t["subspace"]["excess_mse"] for t in unstable],
                          "only marks,mark=x,mark size=3pt,red!75!black,thick", "Unstable")
    scatter = axis(scatter_body,
        r"width=.94\linewidth,height=60mm,xmode=log,ymode=log,"
        + f"xmin={lower},ymin={lower},xmax={upper},ymax={upper},"
        + r"xlabel={AR excess MSE},ylabel={State excess MSE},"
        + r"title={(d) All 150 fits},legend columns=2,"
        + r"legend style={font=\scriptsize,at={(.02,.98)},anchor=north west}")
    figure = r"""% Generated by scripts/lecture05_synthetic_plots.py; edit the generator.
\begin{figure}[p]
\centering
\pgfplotsset{lFivePlot/.style={
 axis lines=left,tick align=outside,grid=major,grid style={black!8},
 tick label style={font=\scriptsize},label style={font=\small},
 title style={font=\small},legend style={font=\scriptsize,draw=none,
 fill=white,cells={anchor=west}},scaled ticks=false}}
""" + top + r"\par\vspace{2mm}" + "\n" + errors + r"\par\vspace{3mm}" + "\n"
    figure += (r"\begin{minipage}[t]{.495\linewidth}" + "\n" + coefficients
               + r"\end{minipage}\hfill\begin{minipage}[t]{.495\linewidth}" + "\n"
               + scatter + r"\end{minipage}" + "\n")
    figure += r"""\caption{The experiment behind \cref{tab:l5-synthetic}.
(a,b) One-step conditional-mean predictions on the first 160 test steps
for the fixed seed 0 and \(T=1024\). Both fitted predictors condition on
the same observed history; the true conditional mean is known from the
generator. The errors exclude the fresh observation noise.
(c) The same fit's lag coefficients: AR(32) is zero beyond lag 32,
whereas the recovered state ties all lags to \(\overline C\overline F^{j-1}\overline L\).
(d) Every seed at all three training sizes. Points below the diagonal favor
the state predictor. Crosses mark unstable state-space generators; they are
included in the table and plot.}
\label{fig:l5-synthetic}
\end{figure}
"""
    Path(output_dir).mkdir(parents=True, exist_ok=True)
    (Path(output_dir) / "lecture05-synthetic-plots.tex").write_text(figure)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    root = Path(__file__).resolve().parents[1]
    parser.add_argument("--results", type=Path,
                        default=root / "documents/figures/lecture05-synthetic.json")
    parser.add_argument("--output-dir", type=Path, default=root / "documents/figures")
    arguments = parser.parse_args()
    write_plots(json.loads(arguments.results.read_text()), arguments.output_dir)
