#!/usr/bin/env python3
"""Summarize every saved experimental condition, including unsuccessful runs."""
from __future__ import annotations

import csv
import json
from collections import defaultdict
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
PLANS = ROOT / "instructor-materials/lecture-plans"
OUT = PLANS / "lecture09-representation-experiment"
INITIAL = {"tanh": PLANS / "lecture09-nn-experiment",
           "ReLU": PLANS / "lecture09-relu-experiment"}
LABELS = {
    "redundant": "redundant scalar", "frozen_relu": "frozen ReLU",
    "trainable_relu": "trained ReLU",
}
for kind, prefix in (("poly", "NN"), ("linear", "linear")):
    for basis in ("mixed", "legendre", "chebyshev"):
        for preprocessing in ("raw", "standard"):
            LABELS[f"{kind}_{basis}_{preprocessing}"] = (
                f"{prefix}: {basis.capitalize()} "
                + ("raw" if preprocessing == "raw" else "std."))


def read(path):
    with path.open(newline="") as stream:
        return list(csv.DictReader(stream))


def groups(rows, keys):
    result = defaultdict(list)
    for row in rows:
        result[tuple(row[key] for key in keys)].append(row)
    return result


def number(value):
    value = float(value)
    if not np.isfinite(value):
        return "--"
    if value != 0 and (abs(value) >= 1000 or abs(value) < 0.0005):
        mantissa, exponent = f"{value:.2e}".split("e")
        return rf"${mantissa}\times10^{{{int(exponent)}}}$"
    return f"{value:.3f}"


def median(rows, key):
    return number(np.median([float(row[key]) for row in rows])) if rows else "--"


def interval(rows, key):
    if not rows:
        return "--"
    values = [float(row[key]) for row in rows]
    return number(min(values)) + "--" + number(max(values))


def table(headers, rows, columns):
    lines = [r"% Generated by scripts/lecture09_auxiliary_report_assets.py.",
             rf"\begin{{tabular}}{{{columns}}}", r"\toprule",
             " & ".join(headers) + r" \\", r"\midrule"]
    lines.extend(" & ".join(row) + r" \\" for row in rows)
    return "\n".join(lines + [r"\bottomrule", r"\end{tabular}", ""])


def make_tables():
    tables, coverage = {}, {}
    coarse_table, repeated_table, pilot_table = [], [], []
    for activation, folder in INITIAL.items():
        coarse = read(folder / "coarse-results.csv")
        repeated = read(folder / "replicated-results.csv")
        coverage[activation] = {"coarse": len(coarse), "repeated": len(repeated)}
        for (depth, width), rows in sorted(groups(coarse, ["depth", "width"]).items(),
                                          key=lambda item: tuple(map(int, item[0]))):
            fits = [r for r in rows if r["final_interpolates"] == "True"]
            coarse_table.append([activation, depth, width,
                                 f"{sum(r['interpolated'] == 'True' for r in rows)}/{len(rows)}",
                                 f"{len(fits)}/{len(rows)}", median(rows, "l2_error"),
                                 number(min(float(r["l2_error"]) for r in fits)) if fits else "--"])
        for (width, rate, scale), rows in sorted(
                groups(repeated, ["width", "learning_rate", "init_scale"]).items(),
                key=lambda item: tuple(map(float, item[0]))):
            fits = [r for r in rows if r["final_interpolates"] == "True"]
            repeated_table.append([activation, width, f"{float(rate):g}", f"{float(scale):g}",
                                   f"{len(fits)}/{len(rows)}", median(rows, "l2_error"),
                                   median(fits, "l2_error"), interval(fits, "l2_error"),
                                   median(rows, "minimum_recorded_l2_error")])
        pilot = json.loads((folder / "pilot-result.json").read_text())
        history = read(folder / "pilot-history.csv")
        best = min(history, key=lambda r: float(r["l2_error"]))
        pilot_table.append([activation, str(pilot["first_interpolation_step"]), str(pilot["steps"]),
                            number(pilot["l2_error"]), number(pilot["maximum_training_residual"]),
                            number(best["l2_error"]), f"{float(best['step']):g}"])
    tables["coarse"] = table(
        ["activation", "depth", "width", "ever fit", "final fit", "median (all)", "best fit"],
        coarse_table, "lrrrrrr")
    tables["repeated"] = table(
        ["activation", "width", "rate", "scale", "fits", "all", "fits only", "fit range", "early"],
        repeated_table, "lrrrrrrrr")
    tables["pilots"] = table(
        ["activation", "first fit", "final step", "final error", "max. residual", "best early", "step"],
        pilot_table, "lrrrrrr")
    development = read(OUT / "development-results.csv")
    selected = json.loads((OUT / "selected-learning-rates.json").read_text())
    rates = sorted({float(r["learning_rate"]) for r in development})
    development_table = []
    for (condition,), rows in groups(development, ["condition"]).items():
        line = [LABELS[condition]]
        for rate in rates:
            subset = [r for r in rows if float(r["learning_rate"]) == rate]
            line.append(f"{sum(r['stable_interpolation'] == 'True' for r in subset)}/{len(subset)}"
                        + "; " + median(subset, "validation_loss"))
        line.append(f"{selected[condition]:g}")
        development_table.append(line)
    tables["development"] = table(
        ["condition"] + [f"rate {rate:g}" for rate in rates] + ["selected"],
        development_table, "lrrrr")
    confirmatory = read(OUT / "confirmatory-results.csv")
    confirmatory_table = []
    for (condition,), rows in groups(confirmatory, ["condition"]).items():
        confirmatory_table.append([
            LABELS[condition], str(len(rows)),
            str(sum(r["stable_interpolation"] == "True" for r in rows)),
            median(rows, "final_l2"), number(np.mean([float(r["final_l2"]) for r in rows])),
            interval(rows, "final_l2"), median(rows, "validation_selected_l2")])
    tables["confirmatory"] = table(
        ["condition", "$N$", "fits", "median", "mean", "range", "selected"],
        confirmatory_table, "lrrrrrr")
    fixed = read(OUT / "followup-fixed-gram.csv")
    fixed_table = []
    for (representation,), rows in groups(fixed, ["representation"]).items():
        label = LABELS.get(representation, representation.replace("_", " "))
        fixed_table.append([label] + [median(rows, key) for key in
                           ("mean_abs_cosine", "max_abs_cosine", "participation_rank")]
                           + [median(rows, key) if rows[0][key] else "--" for key in
                              ("conditional_bias", "conditional_noise_cost")])
    tables["fixed-gram"] = table(
        ["representation", "mean $|C_{ij}|$", "max $|C_{ij}|$", "$r(K)$", "bias", "noise"],
        fixed_table, "lrrrrr")
    learned = read(OUT / "followup-learned-gram.csv")
    learned_table = []
    stages = {"original_selected": "selected early", "original": "original stop", "final": "100,000"}
    for condition in ("redundant", "frozen_relu", "trainable_relu", "poly_mixed_raw"):
        for checkpoint, label in stages.items():
            rows = [r for r in learned if r["condition"] == condition and r["checkpoint"] == checkpoint]
            learned_table.append([LABELS[condition], label, rows[0]["features"]]
                                 + [median(rows, key) for key in
                                    ("mean_abs_cosine", "max_abs_cosine", "participation_rank")])
    tables["learned-gram"] = table(
        ["condition", "checkpoint", "features", "mean $|C_{ij}|$", "max $|C_{ij}|$", "$r(K)$"],
        learned_table, "lllrrr")
    long = read(OUT / "followup-long-training.csv")
    long_table = []
    for (condition,), rows in groups(long, ["condition"]).items():
        long_table.append([LABELS[condition], median(rows, "original_selected_l2"),
                           median(rows, "original_l2"), median(rows, "final_l2"),
                           median(rows, "late_selected_l2"),
                           str(sum(float(r["final_l2"]) < float(r["original_l2"]) for r in rows)),
                           str(sum(float(r["final_l2"]) < float(r["original_selected_l2"]) for r in rows))])
    tables["long"] = table(
        ["condition", "early", "original", "final", "late", "vs. original", "vs. early"],
        long_table, "lrrrrrr")
    coverage.update({"development": len(development), "confirmatory": len(confirmatory),
                     "fixed_gram": len(fixed), "learned_gram": len(learned), "long": len(long),
                     "ridge_paths": len(read(OUT / "followup-ridge-paths.csv")),
                     "ridge_selected": len(read(OUT / "followup-ridge-selected.csv")),
                     "long_history": len(read(OUT / "followup-long-history.csv"))})
    coverage["table_rows"] = {name: text.count(r" \\") - 1 for name, text in tables.items()}
    return tables, coverage


def main():
    tables, coverage = make_tables()
    for name, content in tables.items():
        (OUT / f"auxiliary-{name}-table.tex").write_text(content)
    (OUT / "auxiliary-coverage.json").write_text(json.dumps(coverage, indent=2) + "\n")


if __name__ == "__main__":
    main()
