#!/usr/bin/env python3
"""Render the two saved completion experiments, without simulation or fitting."""
import argparse
import json
import math
from pathlib import Path
from lecture05_synthetic_plots import coordinates, curve, axis

STYLES = {"true": "black", "ar": "orange!85!black",
          "subspace": "courseblue", "state": "courseblue"}
LABELS = {"true": "True process", "ar": "AR", "subspace": "Rank-one state",
          "state": "Full-history state"}
HEADER = r"""% Generated by scripts/lecture05_completion_plots.py.
\begin{figure}[p]
\centering
\pgfplotsset{lFivePlot/.style={
 axis lines=left,tick align=outside,grid=major,grid style={black!8},
 tick label style={font=\scriptsize},label style={font=\small},
 title style={font=\small},legend style={font=\scriptsize,draw=none,
 fill=white,cells={anchor=west}},scaled ticks=false}}
"""


def options(horizon, title, ylabel):
    return (r"width=.97\linewidth,height=72mm,xmin=1,xmax=" + str(horizon)
            + r",xlabel={Completion step},ylabel={" + ylabel + "},title={" + title + "}")


def model_label(case, name):
    if name == "ar":
        return "AR({})".format(len(case["models"][name]["parameters"]["coefficients"]))
    return LABELS[name]


def means_panel(case, names):
    horizon = case["config"]["horizon"]
    xs = list(range(1, horizon+1))
    body = ""
    for name in names:
        dash = ",dashed" if name in ("subspace", "state") else ""
        body += curve(xs, case["models"][name]["mean"],
                      STYLES[name]+",no marks,line width=1pt"+dash, model_label(case, name))
    legend_height = ".75" if "state" in names else ".98"
    return axis(body, options(horizon, "(a) Conditional means", "Mean")
                + r",enlarge y limits=.12,legend style={at={(.98,"
                + legend_height + r")},anchor=north east}")


def sample_bounds(case, names):
    all_values = [v for name in names for key in ("lower", "upper")
                  for v in case["models"][name][key]]
    all_values += [v for name in names for path in case["models"][name]["paths"]
                   for v in path]
    return math.floor(min(all_values)), math.ceil(max(all_values))


def samples_panel(case, name, title, bounds):
    model = case["models"][name]
    horizon = case["config"]["horizon"]
    xs = list(range(1, horizon+1))
    color = STYLES[name]
    polygon = coordinates(xs+xs[::-1], model["upper"]+model["lower"][::-1])
    body = (r"\addplot[draw=none,fill=" + color + r"!12,forget plot] coordinates {"
            + polygon + r"} \closedcycle;" + "\n")
    for i, path in enumerate(model["paths"]):
        opacity = ".65" if i == 0 else ".24"
        body += curve(xs, path, color+",opacity="+opacity
                      +",line width=.45pt,no marks,forget plot")
    body += curve(xs, model["mean"], color+",line width=1.1pt,no marks")
    return axis(body, options(horizon, title, "Observation")
                + f",ymin={bounds[0]},ymax={bounds[1]}")


def grid(panels, caption, label):
    result = HEADER
    for i, panel in enumerate(panels):
        result += r"\begin{minipage}[t]{.485\linewidth}"+"\n"+panel+r"\end{minipage}"+"\n"
        result += (r"\hfill" if i % 2 == 0 else r"\par\vspace{5mm}")+"\n"
    return result+r"\caption{"+caption+"}\n"+r"\label{"+label+"}\n"+r"\end{figure}"+"\n"


def write_plots(result, output_dir):
    fitted, memory = result["fitted"], result["memory"]
    bounds = sample_bounds(fitted, ("true", "ar", "subspace"))
    panels = [means_panel(fitted, ("true", "ar", "subspace"))]
    panels += [samples_panel(fitted, name, f"({letter}) {model_label(fitted, name)}", bounds)
               for name, letter in (("true", "b"), ("ar", "c"), ("subspace", "d"))]
    fit_caption = r"""Completions of the scalar Gaussian process
\(M_{t+1}=0.98M_t+0.18E_t\), \(Z_t=M_t+E_t\),
\(E_t\stackrel{\rm iid}{\sim}\mathcal N(0,1)\).
AR(32) and the rank-one state model are the seed 0, \(T=1024\) fits
from \cref{fig:l5-synthetic}; all models receive the same preceding prefix.
(a) Exact conditional means given this prefix.
(b--d) Three generated continuations per model; the thick line is the
conditional mean and shading is the pointwise 95\% prediction interval.
Corresponding paths share the same standard Gaussian draw at every future
step, scaled by each model's innovation standard deviation. Despite large
noise-driven fluctuations, the paths remain strikingly close because
the models respond similarly to the shared noise.
See \cref{app:completion-experiments} for the protocol."""
    bounds = sample_bounds(memory, ("true", "ar", "state"))
    memory_panels = [means_panel(memory, ("true", "ar", "state"))]
    memory_panels += [samples_panel(memory, name,
                        f"({letter}) {model_label(memory, name)}", bounds)
                     for name, letter in (("true", "b"), ("ar", "c"), ("state", "d"))]
    memory_caption = r"""Memory in completions of the constant-hidden-state
process \(Z_t=U+W_t\), where \(U\sim\mathcal N(0,1)\) and
\(W_t\stackrel{\rm iid}{\sim}\mathcal N(0,1)\) are independent.
The prescribed 1,000-observation prompt is centered near 2.
The panels match \cref{fig:l5-completion-fit}:
(a) conditional means; (b--d) three continuations, conditional means,
and pointwise 95\% prediction intervals, all given the original prompt.
The full-history state model gives the true conditional law, so their
mean curves coincide in (a), and (b,d) have identical paths and bands.
AR(10) recursively uses the optimal ten-observation conditional law.
Corresponding paths share standard Gaussian draws at every future step.
All parameters are known. See \cref{app:completion-experiments}."""
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    (output_dir/"lecture05-completion-fit.tex").write_text(
        grid(panels, fit_caption, "fig:l5-completion-fit"))
    (output_dir/"lecture05-completion-memory.tex").write_text(
        grid(memory_panels, memory_caption, "fig:l5-completion-memory"))


if __name__ == "__main__":
    root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--results", type=Path,
                        default=root/"documents/figures/lecture05-completions.json")
    parser.add_argument("--output-dir", type=Path, default=root/"documents/figures")
    args = parser.parse_args()
    write_plots(json.loads(args.results.read_text()), args.output_dir)
